jobs:
  Job1:
    name: Job Maven
    steps:
      - type: maven
        maven-version: defaultProvidedVersion
        pom-location: pom.xml
        name: Clean test
        goals: clean test
    allow-reuse: false
    checkout-working-directories-only: false
secrets:
  password: credentialsJSON:2b2fca9b-bcad-422c-849a-0800479163b8
